ZDOTDIR="$HOME/.config/zsh"
export ZDOTDIR

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME XDG_DATA_HOME XDG_CACHE_HOME

EDITOR='nvim'
ALTERNATE_EDITOR="vim"
VISUAL=$EDITOR
export EDITOR ALTERNATE_EDITOR VISUAL

PAGER="bat"
MANPAGER="bat"
export PAGER MANPAGER
